Module1 task3
htmlacademy-ecmascript/20140-cinemaddict-15 pull request #3
Opened 2021-07-29 15:30 UTC by wrgraff

2021-07-29 15:33 UTC, wrgraff commented on src/view/films-list.js
> +  <section class="films-list ${isExtra ? 'films-list--extra' : ''}">
Раздражает, что тут создается в коде пробел после класса в том случае, когда модификатор не нужен.

Можно, конечно, написать так:
```suggestion
  <section class="films-list${isExtra ? ' films-list--extra' : ''}">
```

Но это тупость какая-то. HTML будет аккуратнее, зато JS стремный.
Есть какое-то красивое решение? Или это вообще не важно и на форматирование можно забить?

2021-07-29 21:47 UTC, AlexMasterov requested changes

2021-07-29 21:47 UTC, AlexMasterov commented on src/main.js
> +}
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/c9838ba59d69c2f10a568515a6544327741e77a7/src/main.js#L28-L60
</details>

Обрати внимание, что здесь элементы в роли "контейнеров" сначала добавляются в живой DOM (браузер) **и тем самым включаются в его рендеринг**. Далее в них _в циклах_ добавляется _всё_ остальное.

> Если же изменения затрагивают содержимое, структуру документа, положение элементов — происходит [`reflow` (или `relayout`)](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#-appendix)

[`Б 35`](https://up.htmlacademy.ru/ecmascript/15/criteries#b35)
> Множественные DOM-операции производятся на элементах, **которые не добавлены в DOM**

Критерий требует глубокого ревью или автоматического тестирования, где в обоих случаях нужно доказывать факт нарушения, что сложно. Поэтому на защите его никто не проверяет 😃

2021-07-29 21:47 UTC, AlexMasterov commented on src/view/films-list.js
> +    <div class="films-list__container"></div>
` <div class="films-list__container"></div>`

Советую создать отдельной функцией (и далее получать отдельный DOM-элемент).

2021-07-29 21:47 UTC, AlexMasterov commented on src/view/films-list.js
> +    ${isExtra ? '' : '<button class="films-list__show-more">Show more</button>'}
`<button class="films-list__show-more">Show more</button>`

Советую создать отдельной функцией (и далее получать отдельный DOM-элемент).

2021-07-29 21:47 UTC, AlexMasterov commented on src/view/details-comments.js
> +    <ul class="film-details__comments-list"></ul>
`<ul class="film-details__comments-list"></ul>`

Советую создать отдельной функцией (и далее получать отдельный DOM-элемент).

2021-07-29 22:08 UTC, AlexMasterov commented on src/main.js
> +import { createProfileTemplate } from '@view/profile.js';
import { COMMENTS_COUNT } from '@const/comments';
import { createProfileTemplate } from '@view/profile`.js`';

🤔

2021-07-29 23:29 UTC, AlexMasterov commented on src/view/films-list.js
> +  <section class="films-list ${isExtra ? 'films-list--extra' : ''}">
> Есть какое-то красивое решение?

<details>
<summary>Пример некрасивого</summary>

```js
// utils
const mapStyles = (style) => {
  if (typeof style === 'string') {
    return style;
  }
  if (Array.isArray(style)) {
    return style.map(mapStyles).join('').trim();
  }
};

const formatStyle = (...styles) => styles.map(mapStyles).join(' ').trimEnd();
```
```js
// view/films-list.js
const createFilmsListTemplate = (title, { isExtra = false } = {}) => (
  `<section class="${formatStyle`films-list ${isExtra && 'films-list--extra'}`}">
    <h2 class="${formatStyle`films-list__title ${isExtra && 'visually-hidden'}`}">${title}</h2>
  </section>`
);

createFilmsListTemplate('All movies', { isExtra: false });
createFilmsListTemplate('Top rated', { isExtra: true });
```
```html
<section class="films-list">
    <h2 class="films-list__title">All movies</h2>
  </section>

<section class="films-list films-list--extra">
    <h2 class="films-list__title visually-hidden">Top rated</h2>
  </section>
```
</details>

> Или это вообще не важно и на форматирование можно забить?

Для нас это не важно и можно забить 😃

2021-07-29 23:54 UTC, wrgraff commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
А разве не полезен суффикс _Element_ (как и _Template_)?

Меня всегда как-то раздражало, что переменные, содержащие DOM-элемент, ничем не отличаются от остальных. Да и начинаются трудности с именованием.

Например, у меня уже есть переменная `comment`, в которой записан объект с данными, и надо найти DOM-элемент, в который я все это буду рендерить. Не очень понятно, как такую переменную называть, если не `commentElement`.

Мне вообще эта идея с суфиксом показалась удобной, а теперь я в смятении 🤔

2021-07-30 00:06 UTC, wrgraff commented on src/view/films-list.js
> +  <section class="films-list ${isExtra ? 'films-list--extra' : ''}">
_Мы изучим ваш код и вернемся с ответом через неделю_

Как же мне теперь забить, если вон код с решением, и я не смогу спать, пока не пойму что там происходит 😀

2021-07-31 00:42 UTC, AlexMasterov commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
> А разве не полезен суффикс _Element_ (как и _Template_)?

Если _тебе_ полезен суффикс, то просто используй 😃

Критерий про _единообразие_ в именовании переменных.

2021-07-31 00:42 UTC, AlexMasterov commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
> Меня всегда как-то раздражало, что переменные, содержащие DOM-элемент, ничем не отличаются от остальных. Да и начинаются трудности с именованием.

В некоторых контекстах объекты играют определенные роли. Например, функция `render` использует объект типа `*Element` в роли контейнера и в названии переменной выражается его роль (= `container`), а не тип (= `*Element`).

Рассмотри возможность именования переменных в соответствии с их ролью, а не типом. Для структурных типов используй статическую типизацию с type hints (TypeScript).

2021-07-31 01:25 UTC, AlexMasterov commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
> Например, у меня уже есть переменная `comment`, в которой записан объект с данными, и надо найти DOM-элемент, в который я все это буду рендерить. Не очень понятно, как такую переменную называть, если не `commentElement`.

На этом интенсиве для управления DOM-элементами будет используется абстракция на основе класса `AbstractView`. 

Сохранение элементов вне объекта этого класса, например в свойство другого объекта, нарушит его [_инкапсуляцию_](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5#:~:text=%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%B0%20%D0%BF%D0%BE%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8E%20%D0%BA%D0%BE%D0%BD%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D1%8B%D1%85%20%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2). Прямая работа с элементами, в обход его публичного интерфейса, также нарушит его _инкапсуляцию_.

2021-07-31 15:09 UTC, wrgraff commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
Да откуда мне пока что знать что именно мне удобно =)
Для этого надо опыта накопить. А пока можно ориентироваться на рекомендации и пробовать.

Так, ну TypeScript я сейчас в проект вряд ли смогу внедрить, это перегиб 😀
Успеть бы пройтись по всему проекту как следует.

Но думал на тему JSDoc. Может, это поможет, и на данном этапе его будет достаточно?

2021-07-31 19:17 UTC, AlexMasterov approved these changes
Для этого задания сделано достаточно.

Обязательные к исправлению замечания закрыты, а не обязательные можешь учесть по желанию, при выполнении следующего задания.

2021-07-31 19:17 UTC, AlexMasterov commented on src/main.js
> +FILM_LIST_DATA.forEach(( filmsListData ) => renderFilmsList( filmsElement, filmsListData ));
`FILM_LIST_DATA`.forEach(( `filmsListData` ) => renderFilmsList( filmsElement, `filmsListData` ));

Снова странное именование 🤔

2021-07-31 19:17 UTC, AlexMasterov commented on src/utils/render.js
> +  container.insertAdjacentHTML( place, template );
> Но думал на тему JSDoc. Может, это поможет, и на данном этапе его будет достаточно?

Пожалуйста, не надо 😃

Предлагаю оставить этот критерий на проверку случайным проверяющим. Если придерётся, то будет проще исправить по отдельным местам или парировать ссылкой на пример демо проекта.

2021-07-31 19:18 UTC, merged