Module3 task2
htmlacademy-ecmascript/20140-cinemaddict-15 pull request #6
Opened 2021-08-12 21:20 UTC by wrgraff

2021-08-12 23:14 UTC, AlexMasterov requested changes

2021-08-15 01:28 UTC, AlexMasterov requested changes

2021-08-15 01:28 UTC, AlexMasterov commented on src/utils/statistic.js
> +    currentGenre[1] >= genre[1] ? currentGenre : genre
```js
Array.isArray(currentGenre) // true
Array.isArray(genre)        // true
```
Б8

2021-08-15 01:28 UTC, AlexMasterov commented on src/utils/statistic.js
> +    return;
if (`!watchedFilms.length`) {

Непонятная проверка, которая вдобавок работает через неявное приведение.

`return;`

```js
getTopGenre(watchedFilms) // drama
getTopGenre([])           // undefined
```
Функция вместо обещанной `TopGenre` может вернуть `undefined`, т.е значение разного типа; такой результат без доп. _ad-loc_ проверки может небезопасно использоваться в логике или в рендере:

<details>
<summary>Пример</summary>

![image](https://user-images.githubusercontent.com/700213/129463852-fe1e8d83-2b05-4abc-8e6d-4b69be216b42.png)

![image](https://user-images.githubusercontent.com/700213/129463855-5c226958-dee3-4b3b-8175-fc344ba9a859.png)

</details>

2021-08-15 01:28 UTC, AlexMasterov commented on src/view/details-info.js
> +            ${film.genres.map((genre) => (`<span class="film-details__genre">${genre}</span>`)).join('')}
`(`\`<span class="film-details__genre">${genre}</span>\``)`

См. https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/pull/3#discussion_r680395879

2021-08-15 01:28 UTC, AlexMasterov commented on src/view/details-info.js
>            <td class="film-details__term">${film.genres.length > 1 ? 'Genres' : 'Genre'}</td>
`Genres`
`Genre`

На защите проекта могут придраться.

[`Б 5`](https://up.htmlacademy.ru/ecmascript/15/criteries#b5)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2021-08-15 01:28 UTC, AlexMasterov commented on src/view/statistic-rank.js
> +    this._rank = calcTextRank(amount);
this._rank = `calcTextRank(amount)`

Заниматься логикой следует в другом месте, а в _простые_ `views` передать только результаты этих вычислений.

2021-08-15 01:28 UTC, AlexMasterov commented on src/utils/statistic.js
> +export const getStatistic = (films) => {
<details>
<summary>utils/statistic.js</summary>

https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/99d82ba6fd79b29159d795743ea79bcda1d8da8b/src/utils/statistic.js#L1-L34
https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/99d82ba6fd79b29159d795743ea79bcda1d8da8b/src/utils/statistic.js#L36-L44
</details>

Обычно такую задачу решали за один-два цикла и без создания временных массивов 😃

[`Б 34`](https://up.htmlacademy.ru/ecmascript/15/criteries#b34)
> Количество вызовов циклов минимизировано

> Если задачу можно решить за один проход по циклу, вместо нескольких она должна быть решена за один

2021-08-15 14:43 UTC, wrgraff commented on src/utils/statistic.js
> +export const getStatistic = (films) => {
> такую задачу решали за один-два цикла

Кто решал?

> за один-два цикла и без создания временных массивов

У меня есть мысль какие еще способы можно попробовать, но так или иначе я не имею ни малейшего представления как решить задачу за 1 цикл и / или не создавая массив или объект, который бы как-то группировал значения, чтобы получить их количество.

С какой стороны взяться за эту проблему?

2021-08-15 14:43 UTC, wrgraff commented on src/view/details-info.js
>            <td class="film-details__term">${film.genres.length > 1 ? 'Genres' : 'Genre'}</td>
Придраться, что варианты в единственном и множественном числе не выписаны в константы?

Ну, на защите всякое бывает, и до нее еще дожить надо. Я не очень понимаю, как вынос этих названий в константы сделает код лучше или понятнее.
Это меня интересует больше, чем защита: есть ли реальная польза? в чем?

2021-08-15 14:43 UTC, wrgraff commented on src/main.js
> +const renderFilmsListExtra = (extraFilms, title) => {
Это я понимаю.
Мне хотелось избавиться от жуткой функции и сделать все проще.

Насколько важно сейчас заниматься оптимизацией рендера списка фильмов? Не имеет ли смысл оставить это на этап работы с презентером?
Есть ощущение, что там это будет проще и приятнее, чем копаться в файле ~~`frankenstein.js`~~ `main.js`

2021-08-15 14:43 UTC, wrgraff commented on src/main.js
> +if (!films.length) {
🤨

2021-08-15 20:40 UTC, AlexMasterov requested changes

2021-08-15 20:40 UTC, AlexMasterov commented on src/utils/statistic.js
>    ), 0)
<details>
<summary>utils/statistic.js</summary>

https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/99d82ba6fd79b29159d795743ea79bcda1d8da8b/src/utils/statistic.js#L31-L33
</details>

 `(`accumulator `+=` runtime`)`

[`Д 25`](https://up.htmlacademy.ru/ecmascript/15/criteries#d25)
> Оператор присваивания не используется как часть выражения

2021-08-15 20:50 UTC, AlexMasterov commented on src/utils/filter.js
> +export const getFilters = (films) => (
См. https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/pull/6#discussion_r689008381

<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/99d82ba6fd79b29159d795743ea79bcda1d8da8b/src/utils/filter.js#L1-L5
https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/99d82ba6fd79b29159d795743ea79bcda1d8da8b/src/utils/filter.js#L8-L12
</details>

Здесь тоже самое: на каждой итерации создается новый объект.

2021-08-17 01:15 UTC, AlexMasterov commented on src/utils/filter.js
> +export const getFilters = (films) => (
<details>
<summary>utils/filter.js (getFilters)</summary>

https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/blob/802f6e60d5727e4dcbb188cf11aea1162ac8ddfa/src/utils/filter.js#L1-L14
</details>


<details>
<summary>Сравнение с решением другого студента</summary>

```js
// stub
const films = Array.from({ length: 200 }, () => ({
  isInWatchlist: true,
  isWatched: true,
  isFavorite: false,
}));
```
```
getWatchedStats x 1,513,941 ops/sec
getFilters      x 865,633   ops/sec
```
```js
// stub 2
const films = Array.from({ length: 200 }, () => ({
  isInWatchlist: false,
  isWatched: false,
  isFavorite: false,
}));
```
```
getWatchedStats x 3,352,801 ops/sec
getFilters      x 1,414,136 ops/sec
```
</details>

2021-08-17 01:15 UTC, AlexMasterov commented on src/utils/render.js
>    const newElement = document.createElement('div');
new`Element`

```js
newElement instanceof Element // true
```

[`Д 6`](https://up.htmlacademy.ru/ecmascript/15/criteries#d6)
> Используется единый стиль именования переменных

> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

См. также https://github.com/htmlacademy-ecmascript/20140-cinemaddict-15/pull/3#discussion_r679341486

2021-08-17 01:16 UTC, merged

2021-08-17 01:21 UTC, AlexMasterov commented on src/utils/statistic.js
> +  }, 0)
`allRuntime` (`0`) — это примитив, который передается _по значению_.

allRuntime `+=` runtime

Поэтому переприсвоение не имеет смысла и только замеляет работу.

2021-08-17 01:32 UTC, AlexMasterov commented on src/utils/statistic.js
> +    if (amount > key) {
Снова решение перебор всех значений.

if (`amount` > `key`) {

```js
typeof amount // number
typeof key // string
```
_Число_ сравняется со _строкой_ — это не будет правильно работать.

[`Б 24`](https://up.htmlacademy.ru/ecmascript/15/criteries#b24)
> Отсутствуют потенциально некорректные операции

2021-08-17 04:19 UTC, AlexMasterov commented on src/main.js
> +    renderFilmCards(filmsListContainer, filmsToRender.slice( shownFilms, Math.min(shownFilms + FilmListAmountInLine.BASE, filmsToRender.length) ));
См. ТЗ:
> Это удаление карточки не должно каким-либо образом ломать логику кнопки «Show more» или нарушать порядок сортировки

Прошлый подход с функцией `chunk` кроме прочего имел потенциальную проблему для реализации ТЗ. Функция создавала массивы с объектами данных фильмов для последующего показа заранее_, хотя пользователь мог вообще не пользоваться кнопкой `Show more`.

Но по ТЗ пользователь мог с конца списка открыть карточку с фильмом, например, с активной `isFavorite` и, _не закрывая карточки_, использовать фильтр по `Favorites`. Если таких карточек больше 5-и, то открытая не будет показана сразу, _но chunk-массив с ней будет создан_. 

После чего пользователь может просто убрать `isFavorite` у открытой карточке и она уже не должна быть показана по кнопке `Show more`, но будет 😃

2021-08-17 04:45 UTC, AlexMasterov commented on src/utils/statistic.js
> +export const getStatistic = (films) => {
> Кто решал?

Студенты конечно, в том числе мои (их проекты открыты), приводить в пример других было бы нечестно.

> С какой стороны взяться за эту проблему?

```js
{
  watched: 100,
  runtime: 6000,
  genres: {
    drama: 200,
    musical: 100,
    western: 100,
  }
}
```
> Для вывода статистики потребуется не только `topGenre`, но весь список `genres`, отсортированный определенным образом. После сортировки значение первого элемента массива будет `topGenre`. Поэтому находить его отдельно избыточно

Такую структуру можно собрать за _два_ цикла (и без создания временных массивов), например, в два `.reduce`. Попробуй повторить 😃

2021-08-17 04:49 UTC, AlexMasterov commented on src/utils/statistic.js
> +    rank: calcTextRank(watchedFilms.length),
Получается, что `rank` будет отдельно (и _повторно_) вычисляться для `Profile` и для `StatisticRank`?

2021-08-17 05:06 UTC, AlexMasterov commented on src/utils/statistic.js
> +    return;
**Ozon**:

![sshot-2021-08-14-06-05-04](https://user-images.githubusercontent.com/700213/129666734-d69fae8a-da2a-4058-8784-12f6efcf6fc8.jpg)

2021-08-17 09:20 UTC, wrgraff commented on src/utils/statistic.js
> +    return;
Да, я еще вернусь к разбору комментариев в этом ПР.
Но в Ozon правки вносить не буду! 😀